services:
  - type: web
    name: chatbot-militar-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: LANG
        value: C.UTF-8
      - key: LC_ALL
        value: C.UTF-8
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: chatbot-militar-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: UPLOAD_PATH
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: CHUNK_SIZE
        value: 1000
      - key: CHUNK_OVERLAP
        value: 200
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  - name: chatbot-militar-postgres
    databaseName: chatbot_militar
    user: chatbot_user
    plan: free
    ipAllowList: []  # opcional - permite acesso de qualquer IP 